name: Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'WebApplication1/**' # Adjust if your project is in a subfolder
      - 'Dockerfile' # Trigger if Dockerfile changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission to write to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: WebApplication1 # Path to your project folder where Dockerfile or .csproj is
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_CONFIGURATION=Release # If you're using a Dockerfile that leverages build-args
